/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Body to send when finalizing a consent approval. Contains a jwt signed by the issuer which is the requesting serviceprovider. The jwt payload is of type SAConsApprovalFinalizeSp1ToSaJWT
*/
export class ConsentApprovalFinalizeBody {
    /**
    * Signed JWT
    */
    'consApprovalFinalizeJWT': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "consApprovalFinalizeJWT",
            "baseName": "consApprovalFinalizeJWT",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConsentApprovalFinalizeBody.attributeTypeMap;
    }
    
    public constructor() {
    }
}

