/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsentSummaryDTO } from './ConsentSummaryDTO';
import { LocalizedStringDTO } from './LocalizedStringDTO';
import { HttpFile } from '../http/http';

export class ConsentRequestSummaryDTO {
    'id': string;
    'actions': Array<string>;
    'resources': Array<string>;
    'conditions': Array<string>;
    'termsAndConditions': string;
    'purpose': Array<LocalizedStringDTO>;
    'reqServiceProviderId': string;
    'reqServiceProviderName': string;
    'reqPrincipalId': string;
    'reqPrincipalName': string;
    'consServiceProviderId': string;
    'consents'?: Array<ConsentSummaryDTO>;
    'numApproved': number;
    'numRejected': number;
    'responseTotalStatus': ConsentRequestSummaryDTOResponseTotalStatusEnum;
    'numAffectedUsers': number;
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "termsAndConditions",
            "baseName": "termsAndConditions",
            "type": "string",
            "format": ""
        },
        {
            "name": "purpose",
            "baseName": "purpose",
            "type": "Array<LocalizedStringDTO>",
            "format": ""
        },
        {
            "name": "reqServiceProviderId",
            "baseName": "reqServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqServiceProviderName",
            "baseName": "reqServiceProviderName",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqPrincipalId",
            "baseName": "reqPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqPrincipalName",
            "baseName": "reqPrincipalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "consServiceProviderId",
            "baseName": "consServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consents",
            "baseName": "consents",
            "type": "Array<ConsentSummaryDTO>",
            "format": ""
        },
        {
            "name": "numApproved",
            "baseName": "numApproved",
            "type": "number",
            "format": "double"
        },
        {
            "name": "numRejected",
            "baseName": "numRejected",
            "type": "number",
            "format": "double"
        },
        {
            "name": "responseTotalStatus",
            "baseName": "responseTotalStatus",
            "type": "ConsentRequestSummaryDTOResponseTotalStatusEnum",
            "format": ""
        },
        {
            "name": "numAffectedUsers",
            "baseName": "numAffectedUsers",
            "type": "number",
            "format": "double"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ConsentRequestSummaryDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type ConsentRequestSummaryDTOResponseTotalStatusEnum = "PENDING" | "COMPLETED" ;

