/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Contains the URL including the jwt to use to trigger finalization of the consent request in the consenting serviceprovider (can be called by ao web or by requesting service provider) The jwt payload is of type SAConsReqInitializeSaToSp2JWT
*/
export class ConsentRequestUrlDTO {
    'consentRequestURL': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "consentRequestURL",
            "baseName": "consentRequestURL",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConsentRequestUrlDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

