/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsentType } from './ConsentType';
import { PolicyDTO } from './PolicyDTO';
import { HttpFile } from '../http/http';

export class ConsentSearchResultDTO {
    'id': string;
    'reqServiceProviderId': string;
    'reqServiceProviderName': string;
    'consPrincipalId': string;
    'consPrincipalName': string;
    'consServiceProviderId': string;
    'consServiceProviderName': string;
    'status': string;
    'type': ConsentType;
    'createdAt': string;
    'updatedAt'?: string;
    'consentRequestId': string;
    'policies': Array<PolicyDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqServiceProviderId",
            "baseName": "reqServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqServiceProviderName",
            "baseName": "reqServiceProviderName",
            "type": "string",
            "format": ""
        },
        {
            "name": "consPrincipalId",
            "baseName": "consPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consPrincipalName",
            "baseName": "consPrincipalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "consServiceProviderId",
            "baseName": "consServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consServiceProviderName",
            "baseName": "consServiceProviderName",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ConsentType",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "consentRequestId",
            "baseName": "consentRequestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "policies",
            "baseName": "policies",
            "type": "Array<PolicyDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConsentSearchResultDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

