/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Contains the URL including the jwt to use to trigger finalization of the consent request in the requesting serviceprovider (can be called by ao web or by consenting service provider) The jwt payload is of type SAConsReqFinalizeSaToSp1JWT
*/
export class ConsentRequestFinalizeUrlDTO {
    'consReqFinalizeURL': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "consReqFinalizeURL",
            "baseName": "consReqFinalizeURL",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConsentRequestFinalizeUrlDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

