/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsentType } from './ConsentType';
import { PolicySummaryDTO } from './PolicySummaryDTO';
import { HttpFile } from '../http/http';

export class ConsentSummaryDTO {
    'id': string;
    'type': ConsentType;
    'consPrincipalId': string;
    'consPrincipalName': string;
    'policy'?: Array<PolicySummaryDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ConsentType",
            "format": ""
        },
        {
            "name": "consPrincipalId",
            "baseName": "consPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consPrincipalName",
            "baseName": "consPrincipalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "Array<PolicySummaryDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConsentSummaryDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

