/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateResourceTagTemplateDTO } from './CreateResourceTagTemplateDTO';
import { HttpFile } from '../http/http';

export class CreateResourceTemplateDTO {
    'id'?: string;
    'policyActionTemplateId'?: string;
    'tenantName': string;
    'systemName': string;
    'resourceTagTemplates': Array<CreateResourceTagTemplateDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "policyActionTemplateId",
            "baseName": "policyActionTemplateId",
            "type": "string",
            "format": ""
        },
        {
            "name": "tenantName",
            "baseName": "tenantName",
            "type": "string",
            "format": ""
        },
        {
            "name": "systemName",
            "baseName": "systemName",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceTagTemplates",
            "baseName": "resourceTagTemplates",
            "type": "Array<CreateResourceTagTemplateDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateResourceTemplateDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

