/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DebugDTOExampleKeyPair {
    '_private': string;
    '_public': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_private",
            "baseName": "private",
            "type": "string",
            "format": ""
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DebugDTOExampleKeyPair.attributeTypeMap;
    }
    
    public constructor() {
    }
}

