/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A Legal Entity is a person, company or system (here refered to as \"an entity\"). The origin (where they are stored / identified) is most often in one of the ServiceProviders. Thus the combination origin_serviceprovider_id (~\"application id\") and origin_enity_id (~\"user id\").
*/
export class LegalEntityDTO {
    'originServiceProviderId': string;
    'originEntityId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "originServiceProviderId",
            "baseName": "originServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "originEntityId",
            "baseName": "originEntityId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LegalEntityDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

