/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsentRequestSearchResultDTO } from './ConsentRequestSearchResultDTO';
import { HttpFile } from '../http/http';

/**
* Includes search result and info about pagination
*/
export class PaginationResultDTOConsentRequestSearchResultDTO {
    /**
    * List of search result items. Empty if no items found
    */
    'list': Array<ConsentRequestSearchResultDTO>;
    /**
    * Total number of items matching the search. Will equal taken if no take was specified in the search parameters. Use this to determine if more items can be fetched with next interval of skip and take
    */
    'totalCount': number;
    /**
    * Number of items returned
    */
    'taken': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "list",
            "baseName": "list",
            "type": "Array<ConsentRequestSearchResultDTO>",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": "double"
        },
        {
            "name": "taken",
            "baseName": "taken",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return PaginationResultDTOConsentRequestSearchResultDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

