/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceTagDTO } from './ResourceTagDTO';
import { HttpFile } from '../http/http';

export class PolicyResourceDTO {
    'tenant': string;
    'system': string;
    'tags': Array<ResourceTagDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenant",
            "baseName": "tenant",
            "type": "string",
            "format": ""
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<ResourceTagDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PolicyResourceDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

