/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PolicySummaryDTO {
    'reqServiceProviderId': string;
    'reqPrincipalId': string;
    'consServiceProviderId': string;
    'consPrincipalId': string;
    'actions': Array<string>;
    'resources': Array<string>;
    'conditions': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reqServiceProviderId",
            "baseName": "reqServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqPrincipalId",
            "baseName": "reqPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consServiceProviderId",
            "baseName": "consServiceProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consPrincipalId",
            "baseName": "consPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PolicySummaryDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

