/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PolicyActionDTO } from './PolicyActionDTO';
import { PolicyConditionDTO } from './PolicyConditionDTO';
import { PolicyResourceDTO } from './PolicyResourceDTO';
import { HttpFile } from '../http/http';

export class PolicyDTO {
    'actions': Array<PolicyActionDTO>;
    'conditions': Array<PolicyConditionDTO>;
    'resources': Array<PolicyResourceDTO>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<PolicyActionDTO>",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<PolicyConditionDTO>",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<PolicyResourceDTO>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PolicyDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

