/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Sort order of the search result. This is applied before skip and take. Only one sort order is supported. Leave out to return in the order decided by the database (possibly id)
*/
export class SearchConsentsDTOSort {
    'status'?: SearchConsentsDTOSortStatusEnum;
    'updatedAt'?: SearchConsentsDTOSortUpdatedAtEnum;
    'createdAt'?: SearchConsentsDTOSortCreatedAtEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SearchConsentsDTOSortStatusEnum",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "SearchConsentsDTOSortUpdatedAtEnum",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "SearchConsentsDTOSortCreatedAtEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchConsentsDTOSort.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type SearchConsentsDTOSortStatusEnum = "asc" | "desc" ;
export type SearchConsentsDTOSortUpdatedAtEnum = "asc" | "desc" ;
export type SearchConsentsDTOSortCreatedAtEnum = "asc" | "desc" ;

