/**
 * @ao/ah-api
 * Telia Smart Access API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SingleProviderConsentDTO {
    'reqPrincipalName': string;
    'reqPrincipalId': string;
    'consPrincipalName': string;
    'consPrincipalId': string;
    'actions': Array<string>;
    'resources': Array<string>;
    'conditions': Array<string>;
    'termsAndConditions'?: string;
    /**
    * Set this time when recording a historical consent. Format is Unix time (seconds since epoch)
    */
    'consentedAt'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reqPrincipalName",
            "baseName": "reqPrincipalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqPrincipalId",
            "baseName": "reqPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "consPrincipalName",
            "baseName": "consPrincipalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "consPrincipalId",
            "baseName": "consPrincipalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "termsAndConditions",
            "baseName": "termsAndConditions",
            "type": "string",
            "format": ""
        },
        {
            "name": "consentedAt",
            "baseName": "consentedAt",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return SingleProviderConsentDTO.attributeTypeMap;
    }
    
    public constructor() {
    }
}

