"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AOEmbeddedEvents = exports.SA_EMBEDDED_EVENT_MESSAGE_DELIMITER = void 0;
exports.SA_EMBEDDED_EVENT_MESSAGE_DELIMITER = '::';
const SA_EMBEDDED_EVENT_PREFIX = 'AO_EMBEDDED';
exports.AOEmbeddedEvents = {
    INIT: `${SA_EMBEDDED_EVENT_PREFIX}${exports.SA_EMBEDDED_EVENT_MESSAGE_DELIMITER}INIT`,
    SUBMITTING: `${SA_EMBEDDED_EVENT_PREFIX}${exports.SA_EMBEDDED_EVENT_MESSAGE_DELIMITER}SUBMITTING`,
    COMPLETE: `${SA_EMBEDDED_EVENT_PREFIX}${exports.SA_EMBEDDED_EVENT_MESSAGE_DELIMITER}COMPLETE`,
    ERROR: `${SA_EMBEDDED_EVENT_PREFIX}${exports.SA_EMBEDDED_EVENT_MESSAGE_DELIMITER}ERROR`
};
//# sourceMappingURL=embedded.js.map