"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventLevel = exports.EventType = exports.SCWalletEventTopic = exports.SAAdminEventTopic = exports.SAEventKey = exports.SAEventTopic = void 0;
exports.SAEventTopic = "ao-api-event";
exports.SAEventKey = "ao-event-key";
exports.SAAdminEventTopic = "ao-admin-api-event";
exports.SCWalletEventTopic = "sc-wallet-api-event";
var EventType;
(function (EventType) {
    EventType["REQUEST_SUCCESS"] = "request_success";
    EventType["REQUEST_FAIL"] = "request_fail";
    EventType["AUTHENTICATION_FAIL"] = "authentication_fail";
    EventType["AUTHENTICATION_FLOW_FAIL"] = "authentication_flow_fail";
    EventType["INITIALIZE_CR_SUCCESS"] = "initialize_consent_request_success";
    EventType["INITIALIZE_CR_ACCESS_FAIL"] = "initialize_consent_request_access_fail";
    EventType["FINALIZE_CR_SUCCESS"] = "finalize_consent_request_success";
    EventType["FINALIZE_CR_ACCESS_FAIL"] = "finalize_consent_request_access_fail";
    EventType["COMPLETED_CR_SUCCESS"] = "completed_consent_request_success";
    EventType["INITIALIZE_CONSENT_SUCCESS"] = "initialize_consent_success";
    EventType["INITIALIZE_CONSENT_ACCESS_FAIL"] = "initialize_consent_access_fail";
    EventType["FINALIZE_CONSENT_SUCCESS"] = "finalize_consent_success";
    EventType["FINALIZE_CONSENT_ACCESS_FAIL"] = "finalize_consent_access_fail";
    EventType["AUTH_TICKET_SUCCESS"] = "create_authorization_ticket_success";
    EventType["AUTH_TICKET_ACCESS_FAIL"] = "create_authorization_ticket_access_fail";
    EventType["FETCH_CR_ACCESS_FAIL"] = "fetch_consent_request_access_fail";
    EventType["FETCH_CONSENT_ACCESS_FAIL"] = "fetch_consent_access_fail";
    EventType["DELETE_CR_SUCCESS"] = "delete_consent_request_success";
    EventType["DELETE_CR_FAIL"] = "delete_consent_request_failed";
    EventType["DELETE_CONSENT_SUCCESS"] = "delete_consent_success";
    EventType["REGISTER_SERVICEPROVIDER_SUCCESS"] = "register_serviceprovider_success";
    EventType["DELETE_SERVICEPROVIDER_SUCCESS"] = "delete_serviceprovider_success";
    EventType["UPDATE_SERVICEPROVIDER_SUCCESS"] = "update_serviceprovider_success";
    EventType["SEARCH_CR_ACCESS_FAIL"] = "search_consent_request_access_fail";
    EventType["SEARCH_CONSENT_ACCESS_FAIL"] = "search_consent_access_fail";
    EventType["MANAGE_ACTION_TEMPLATES"] = "manage_action_templates_fail";
    EventType["MANAGE_SERVICE_PROVIDER"] = "manage_service_provider_fail";
    EventType["VALIDATION_ACTION_FAIL"] = "validation_action_fail";
    EventType["REVOKE_CONSENT_ACCESS_FAIL"] = "revoke_consent_fail";
    EventType["REVOKE_CONSENT_SUCCESS"] = "revoke_consent_success";
})(EventType = exports.EventType || (exports.EventType = {}));
var EventLevel;
(function (EventLevel) {
    EventLevel["INFO"] = "info";
    EventLevel["ALERT"] = "alert";
})(EventLevel = exports.EventLevel || (exports.EventLevel = {}));
//# sourceMappingURL=events.js.map